# Path to your oh-my-zsh configuration.
#ZSH=$HOME/.oh-my-zsh
ZSH=$HOME/.dotfiles/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
source ${HOME}/.dotfiles/z/z.sh
# Customize to your needs...
export PATH=$PATH:/Users/foocoder/.rvm/gems/ruby-1.9.3-p392/bin:/Users/foocoder/.rvm/gems/ruby-1.9.3-p392@global/bin:/Users/foocoder/.rvm/rubies/ruby-1.9.3-p392/bin:/Users/foocoder/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/sbin:/Users/foocoder/bin
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=/Users/foocoder/develop/apache-tomcat-7.0.37/bin:$PATH
export PATH=/Users/foocoder/develop/android-sdk-macosx/platform-tools:$PATH
export PATH=/usr/local/nginx/nginx8011/sbin:$PATH
export PATH=/Users/foocoder/develop/github/git-imerge:$PATH
export PATH=/Users/foocoder/develop/dart/dart-sdk/bin:$PATH
export DART_SDK=/Users/foocoder/develop/dart/dart-sdk/
#vim mode
#bindkey -v


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
